apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommender
  labels:                       #This label has no such high value till now in the deployment.
    app: movie-recommender
spec:
  replicas: 1
  selector:                      #this connects the template,service,other things to deployment. This is the important part.
    matchLabels:                 #if you change the selector label name then you have to change the other labels that is reffering
      app: movie-recommender      #to current label.
  template:
    metadata:
      labels:
        app: movie-recommender
    spec:
      containers:
      - name: movie-recommender
        image: pranit007/movie-recommender
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m