apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommender
  labels:                          #This label is not necessary in this deployment file.
    app: movie-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-recommender
  template:
    metadata:
      labels:
        app: movie-recommender
    spec:
      containers:
      - name: movie-recommender
        image: pranit007/movie-recommender
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
