apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: movie-recommender
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: movie-recommender
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50